include: package:very_good_analysis/analysis_options.yaml

analyzer: 
  exclude:
    - lib/generated/**
    - '**/*.mocks.dart'

linter: 
  rules:
    avoid_dynamic_calls: false
    one_member_abstracts: false
    avoid_redundant_argument_values: false
    sort_pub_dependencies: false
    type_annotate_public_apis: false
    public_member_api_docs: false
    directives_ordering: false