name: weather_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  # Feature dependencies
  get_it: ^7.6.0
  get: ^4.6.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0
  very_good_analysis: ^5.0.0+1
  analyzer: ^6.0.0
  json_serializable: ^6.6.0
  build_runner: ^2.3.3
  mockito: ^5.4.2

dependency_overrides:
  analyzer: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

import_sorter:
  emojis: true
  ignored_files:
    - '\.g\.dart'
    - '\.mocks\.dart'