// Mocks generated by Mockito 5.4.2 from annotations
// in weather_app/test/features/current_weather/data/repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/core/domain/model/saved_location_model.dart' as _i5;
import 'package:weather_app/features/current_weather/data/repository.dart'
    as _i3;
import 'package:weather_app/features/current_weather/domain/model/current_weather_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCurrentWeatherModel_0 extends _i1.SmartFake
    implements _i2.CurrentWeatherModel {
  _FakeCurrentWeatherModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CurrentWeatherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrentWeatherRepository extends _i1.Mock
    implements _i3.CurrentWeatherRepository {
  @override
  _i4.Future<_i2.CurrentWeatherModel> getCurrentWeather(
          {required _i5.SavedLocationModel? savedLocationModel}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentWeather,
          [],
          {#savedLocationModel: savedLocationModel},
        ),
        returnValue: _i4.Future<_i2.CurrentWeatherModel>.value(
            _FakeCurrentWeatherModel_0(
          this,
          Invocation.method(
            #getCurrentWeather,
            [],
            {#savedLocationModel: savedLocationModel},
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.CurrentWeatherModel>.value(
            _FakeCurrentWeatherModel_0(
          this,
          Invocation.method(
            #getCurrentWeather,
            [],
            {#savedLocationModel: savedLocationModel},
          ),
        )),
      ) as _i4.Future<_i2.CurrentWeatherModel>);
}
